import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createStore } from '../lib/store.mjs';
import { writeLegacyAlphaFixture } from './alpha-fixture.mjs';

const fixture = () => { const file = path.join(mkdtempSync(path.join(tmpdir(),'alpha-modeler-')),'dashboard.json'); writeLegacyAlphaFixture(file); return {file,store:createStore(file)}; };
test('Просмотр и сохранение без правок не меняют файл; заметки, детали V2 и история переживают повторный запуск', () => {
  const {file,store} = fixture(); const alpha = store.getPortfolio().alphas[0]; const original = readFileSync(file,'utf8');
  store.getPortfolio(); store.alphaHistory(alpha.id); store.alphaBackup();
  store.updatePortfolio('updateAlpha',{...alpha,expectedRevision:0});
  assert.equal(readFileSync(file,'utf8'),original);
  const input = {...alpha,description:'Моя новая заметка\nсо второй строкой',evidence:'Пока неизвестно',nextStep:'Проверить потребность',reviewDate:'2026-10-07',whyImportant:'Польза клиенту',adaptedAlpha:'Клиенты проекта',area:'Надсистема',source:'Мой справочник',metaAdaptation:'Конкретизация',systemTime:'Оба',attention:'Проверить позже',expectedRevision:0};
  const result = store.updatePortfolio('updateAlpha',input);
  const changed = result.alphas.find(item=>item.id===alpha.id);
  assert.equal(changed.revision,1); assert.equal(changed.reviewDate,'2026-10-07');
  assert.equal(store.alphaHistory(alpha.id).length,2);
  const saved = readFileSync(file,'utf8');
  store.updatePortfolio('updateAlpha',{...changed,expectedRevision:1});
  assert.equal(readFileSync(file,'utf8'),saved);
  const reopened = createStore(file); assert.equal(reopened.getPortfolio().alphas[0].description,input.description);
  assert.equal(reopened.alphaHistory(alpha.id)[0].snapshot.description,alpha.description);
  assert.equal(reopened.alphaHistory(alpha.id)[1].snapshot.description,input.description);
  assert.deepEqual(reopened.getWeek('2026-10-05').entries,[]);
});
test('Запись только с именем разрешена; другая вкладка не перезаписывает правки, старая форма сохраняет новые поля', () => {
  const {file,store} = fixture();
  const result = store.updatePortfolio('createAlpha',{projectId:'test-project',zoneId:'customers',uniqueName:'Новый конкретный объект',state:'empty',description:'Начальная заметка'});
  const alpha = result.alphas.at(-1); assert.equal(alpha.typeName,''); assert.equal(alpha.filledDate,null);
  store.updatePortfolio('updateAlpha',{...alpha,expectedRevision:1,reviewDate:'2026-10-08',whyImportant:'Пользовательский интерес'});
  const after = readFileSync(file,'utf8');
  assert.throws(()=>store.updatePortfolio('updateAlpha',{...alpha,expectedRevision:1,description:'Устаревшая вкладка'}),/другой вкладке/);
  assert.equal(readFileSync(file,'utf8'),after);
  const oldForm = {...store.getPortfolio().alphas.at(-1),description:'Правка из Workflow'};
  delete oldForm.reviewDate; delete oldForm.whyImportant;
  store.updatePortfolio('updateAlpha',oldForm);
  assert.equal(store.getPortfolio().alphas.at(-1).reviewDate,'2026-10-08');
  assert.equal(store.getPortfolio().alphas.at(-1).whyImportant,'Пользовательский интерес');
});
test('Импорт сначала проверяет без записи; повтор не дублирует, конфликт сохраняет локальный текст; повреждённый файл атомарно отклоняется', () => {
  const source=fixture(); const destination=fixture(); const alpha=source.store.getPortfolio().alphas[0];
  source.store.updatePortfolio('createAlpha',{projectId:'test-project',zoneId:'customers',parentId:alpha.id,uniqueName:'Подобъект для переноса',typeName:'',state:'empty',description:'Экспортируемая заметка',reviewDate:'2026-10-09'});
  const backup=source.store.alphaBackup(); const original=readFileSync(destination.file,'utf8');
  assert.equal(destination.store.importAlphas(backup).added,1); assert.equal(readFileSync(destination.file,'utf8'),original);
  assert.equal(destination.store.importAlphas(backup,true).added,1);
  const reopened=createStore(destination.file); assert.equal(reopened.getPortfolio().alphas.length,4);
  assert.equal(reopened.getPortfolio().alphas.at(-1).parentId,alpha.id);
  assert.equal(reopened.importAlphas(backup,true).added,0);
  backup.alphas[0].description='Отличающаяся импортная заметка';
  assert.equal(reopened.importAlphas(backup,true).conflicts.length,1);
  assert.equal(reopened.getPortfolio().alphas[0].description,alpha.description);
  const before=readFileSync(destination.file,'utf8');
  const invalid=structuredClone(backup); invalid.alphas.push({...invalid.alphas.at(-1),id:'invalid-new',uniqueName:'Ошибка даты',reviewDate:'2026-02-31'});
  assert.throws(()=>reopened.importAlphas(invalid,true),/дат/); assert.equal(readFileSync(destination.file,'utf8'),before);
  const cycle=structuredClone(backup); cycle.alphas.push({...cycle.alphas.at(-1),id:'cycle',uniqueName:'Цикл',parentId:'cycle'});
  assert.throws(()=>reopened.importAlphas(cycle,true),/цикл/);
});
test('Перенос проекта и его истории не меняет нормы и часы получателя', () => {
  const source=fixture(); const destination=fixture();
  source.store.updatePortfolio('createProject',{name:'Свой проект',status:'active',phase:'pre_operation',zoneIds:['customers']});
  const project=source.store.getPortfolio().projects.at(-1);
  source.store.updatePortfolio('createAlpha',{projectId:project.id,zoneId:'customers',uniqueName:'Объект своего проекта',state:'empty',description:'Первая версия'});
  const alpha=source.store.getPortfolio().alphas.at(-1);
  source.store.updatePortfolio('updateAlpha',{...alpha,description:'Вторая версия',expectedRevision:1});
  destination.store.updateTargets('2026-10-05',{reading:12});
  destination.store.addEntry({metricId:'reading',date:'2026-10-06',amount:1,title:'Свой учёт'});
  const before=destination.store.getWeek('2026-10-05'); const backup=source.store.alphaBackup();
  destination.store.importAlphas(backup,true);
  assert.equal(destination.store.getPortfolio().projects.at(-1).name,'Свой проект');
  assert.ok(destination.store.alphaHistory(alpha.id).some(entry=>entry.snapshot.description==='Первая версия'));
  assert.ok(destination.store.alphaHistory(alpha.id).some(entry=>entry.snapshot.description==='Вторая версия'));
  assert.deepEqual(destination.store.getWeek('2026-10-05').metrics,before.metrics);
  assert.deepEqual(destination.store.getWeek('2026-10-05').entries,before.entries);
});
